export const CREDIT_MANAGEMENT_TOKENS = {
  CREDIT_REQUEST_REPOSITORY: Symbol('CM_CREDIT_REQUEST_REPOSITORY'),
  LOAN_REPOSITORY: Symbol('CM_LOAN_REPOSITORY'),
  INSTALLMENT_REPOSITORY: Symbol('CM_INSTALLMENT_REPOSITORY'),
  LOAN_REFINANCE_REPOSITORY: Symbol('CM_LOAN_REFINANCE_REPOSITORY'),
  LOAN_CHARGE_REPOSITORY: Symbol('CM_LOAN_CHARGE_REPOSITORY'),
  PENALTY_POLICY_REPOSITORY: Symbol('CM_PENALTY_POLICY_REPOSITORY'),
  LATE_FEE_REPOSITORY: Symbol('CM_LATE_FEE_REPOSITORY'),
  LOAN_HISTORY_REPOSITORY: Symbol('CM_LOAN_HISTORY_REPOSITORY'),
} as const;

