export const IAM_TOKENS = {
  USER_REPOSITORY: Symbol('IAM_USER_REPOSITORY'),
  ROLE_REPOSITORY: Symbol('IAM_ROLE_REPOSITORY'),
  USER_ROLE_REPOSITORY: Symbol('IAM_USER_ROLE_REPOSITORY'),
  PASSWORD_HASHER: Symbol('IAM_PASSWORD_HASHER'),
} as const;

